### ISSUE TITLE
Countdown Timer with Bar/Circle

### ISSUE THREAD

**Issue by kasgithub8** [JayP718/Countdown_Timer#2]
Hi Jay,

I really like your plugin and would love to use it.
My little "project" requires a visual presentation in addition to the timer.
Obviously, we can't add a JavaScript embed to Budibase so this is the closest to meet the requirements.
Do you think this is possible?

Sincerely,
Kevin

**Comment by JayP718** [comment]
Hey there,

Thanks! I can take a look.

Are you looking for something like this

https://www.w3schools.com/w3css/w3css_progressbar.asp


Or more like a progress ring?

Best,

Jay

**Comment by kasgithub8** [comment]
> Are you looking for something like this
> 
> https://www.w3schools.com/w3css/w3css_progressbar.asp

Exactly like this! Just with the Timer of course.

**Comment by JayP718** [comment]
Sure, give me a few days

**Comment by JayP718** [comment]
Hi @kasgithub8,

So I began working on this and started thinking about your request a bit more.

So for there to be a progress bar the user would have to know the the start date/time, end date/time. and current time until end.

Because the progress bar for a timer with 20 seconds total and only 10 seconds remaining will look very different from a timer that's for 30 days and only 10 seconds remaining. I think I know how to account for it but do you mind sharing some more information about your specific use case? 

And would something like this work for your needs? That way the button itself is the progress bar. I think it gives it a cleaner look but what are you thoughts?

<img width="258" alt="image" src="https://user-images.githubusercontent.com/42209052/206916791-e6009f0e-b306-4327-8aa5-d957b9cef15a.png">

**Comment by kasgithub8** [comment]
> I think I know how to account for it but do you mind sharing some more information about your specific use case?
> 

My use case would be a 30 second timer that stops after the time runs out.
A cool addition to it would be pre-entering the time in the builder so that it auto-starts when entering site.

> And would something like this work for your needs? That way the button itself is the progress bar. I think it gives it a cleaner look but what are you thoughts?

As long as the timer is adjustable, it's nice because you can always change the size and colors of the button.

**Comment by kasgithub8** [comment]
Hi @JayP718, 

not to pressure you, just wanna ask if there are any updates on this?
I appreciate your help very much!

Best,
Kevin

**Comment by kasgithub8** [comment]
Hi @JayP718,

any updates?

Sincerely,
Kevin

**Comment by JayP718** [comment]
Hi @kasgithub8,

I've created a new plugin. It's a little different from this plugin but it should do the trick. Let me know if it works for you and I'll close this feature request.

https://github.com/JayP718/timer_2_bb_plugin

**Comment by kasgithub8** [comment]
Hi @JayP718,

your new plugin is so beautiful! It works like a charm!
You should definitely release it for everybody.

Thanks for your help, I appreciate your work!

Sincerely,
Kevin

**Comment by JayP718** [comment]
Glad it works! Thanks, enjoy :)
